# Generated by Django 6.0.2 on 2026-02-17 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_code', models.CharField(max_length=50, unique=True)),
                ('asset_name', models.CharField(max_length=200)),
                ('asset_kind', models.CharField(choices=[('PC', 'PC'), ('DEVICE', 'DEVICE'), ('LICENSE', 'LICENSE'), ('OTHER', 'OTHER')], max_length=20)),
                ('status', models.CharField(choices=[('IN_USE', 'IN_USE'), ('MAINTENANCE', 'MAINTENANCE'), ('DISPOSED', 'DISPOSED')], default='IN_USE', max_length=20)),
                ('budget_link_status', models.CharField(choices=[('UNLINKED', 'UNLINKED'), ('LINKED', 'LINKED')], default='UNLINKED', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_expiry_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetCategoryL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuthLockout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('failed_count', models.IntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiscal_year', models.IntegerField()),
                ('budget_category', models.CharField(max_length=100)),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config_code', models.CharField(max_length=50, unique=True)),
                ('config_name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle_code', models.CharField(max_length=20, unique=True)),
                ('cycle_year', models.IntegerField()),
                ('cycle_month', models.IntegerField()),
                ('status', models.CharField(choices=[('PLANNED', 'PLANNED'), ('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], default='PLANNED', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_code', models.CharField(max_length=30, unique=True)),
                ('project_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor_code', models.CharField(max_length=30, unique=True)),
                ('vendor_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetAttributeMultiValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multi_attr_type', models.CharField(choices=[('MULTI_01', 'MULTI_01'), ('MULTI_02', 'MULTI_02')], max_length=20)),
                ('value', models.CharField(max_length=500)),
                ('sort_order', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_requests.asset')),
            ],
        ),
        migrations.CreateModel(
            name='AssetAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cls_attr_01', models.CharField(blank=True, max_length=50)),
                ('cls_attr_02', models.CharField(blank=True, max_length=50)),
                ('cls_attr_03', models.CharField(blank=True, max_length=50)),
                ('cls_attr_04', models.CharField(blank=True, max_length=50)),
                ('cls_attr_05', models.CharField(blank=True, max_length=50)),
                ('location_attr_01', models.CharField(blank=True, max_length=100)),
                ('location_attr_02', models.CharField(blank=True, max_length=100)),
                ('date_attr_01', models.DateField(blank=True, null=True)),
                ('date_attr_02', models.DateField(blank=True, null=True)),
                ('date_attr_03', models.DateField(blank=True, null=True)),
                ('free_text_attr_01', models.CharField(blank=True, max_length=200)),
                ('free_text_attr_02', models.CharField(blank=True, max_length=200)),
                ('free_text_attr_03', models.CharField(blank=True, max_length=500)),
                ('memo_attr_01', models.TextField(blank=True)),
                ('memo_attr_02', models.TextField(blank=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account_requests.asset')),
                ('person_attr_01', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person_attr_02', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person_attr_03', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetCategoryM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('category_l', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account_requests.assetcategoryl')),
            ],
            options={
                'unique_together': {('category_l', 'code')},
            },
        ),
        migrations.CreateModel(
            name='AssetCategoryS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('category_m', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account_requests.assetcategorym')),
            ],
            options={
                'unique_together': {('category_m', 'code')},
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='category_s',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account_requests.assetcategorys'),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account_requests.assettype'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_table', models.CharField(max_length=100)),
                ('target_id', models.BigIntegerField()),
                ('action', models.CharField(max_length=30)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('change_summary', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account_requests.budget'),
        ),
        migrations.CreateModel(
            name='ConfigurationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account_requests.asset')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_requests.configuration')),
            ],
        ),
        migrations.CreateModel(
            name='DisposalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_text', models.TextField(blank=True)),
                ('reject_reason', models.TextField(blank=True)),
                ('disposal_status', models.CharField(choices=[('REQUESTED', 'REQUESTED'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='REQUESTED', max_length=20)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disposal_approvals', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account_requests.asset')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposal_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExecutedBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_date', models.DateField()),
                ('executed_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_requests.budget')),
            ],
        ),
        migrations.AddField(
            model_name='budget',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account_requests.project'),
        ),
        migrations.AddField(
            model_name='asset',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account_requests.vendor'),
        ),
        migrations.CreateModel(
            name='InventoryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('difference_type', models.CharField(choices=[('MISSING', 'MISSING'), ('EXCESS', 'EXCESS'), ('STATUS_DIFF', 'STATUS_DIFF')], max_length=20)),
                ('correction_status', models.CharField(choices=[('OPEN', 'OPEN'), ('IN_PROGRESS', 'IN_PROGRESS'), ('DONE', 'DONE')], default='OPEN', max_length=20)),
                ('correction_note', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account_requests.asset')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_requests.inventorycycle')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_registered', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('cycle', 'asset')},
            },
        ),
    ]
