# Generated by Django 6.0.2 on 2026-02-17 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardKPIDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kpi_date', models.DateField(unique=True)),
                ('budget_consumption_rate', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('unlinked_asset_count', models.IntegerField(default=0)),
                ('maintenance_overdue_count', models.IntegerField(default=0)),
                ('inventory_diff_count', models.IntegerField(default=0)),
                ('configuration_completeness_rate', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LicensePool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('license_name', models.CharField(max_length=200)),
                ('total_count', models.IntegerField(default=0)),
                ('used_count', models.IntegerField(default=0)),
                ('remaining_count', models.IntegerField(default=0)),
                ('contract_expiry_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LicenseAllocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_count', models.IntegerField(default=1)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account_requests.asset')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_requests.licensepool')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SENT', 'SENT'), ('FAILED', 'FAILED')], default='PENDING', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserPCAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('os_name', models.CharField(max_length=100)),
                ('spec_text', models.CharField(blank=True, max_length=500)),
                ('warranty_expiry_date', models.DateField(blank=True, null=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='account_requests.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetBudgetMonitorDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monitor_date', models.DateField()),
                ('dept_code', models.CharField(blank=True, max_length=30)),
                ('unlinked_count', models.IntegerField(default=0)),
                ('threshold_count', models.IntegerField(default=0)),
                ('is_threshold_exceeded', models.BooleanField(default=False)),
                ('category_s', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account_requests.assetcategorys')),
            ],
            options={
                'unique_together': {('monitor_date', 'dept_code', 'category_s')},
            },
        ),
        migrations.CreateModel(
            name='InventoryTargetSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_at_snapshot', models.CharField(max_length=20)),
                ('budget_link_status_at_snapshot', models.CharField(max_length=20)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account_requests.asset')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_requests.inventorycycle')),
            ],
            options={
                'unique_together': {('cycle', 'asset')},
            },
        ),
    ]
