# Generated by Django 6.0.2 on 2026-02-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_requests', '0003_loanhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCategoryL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BudgetCategoryM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('category_l', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account_requests.budgetcategoryl')),
            ],
            options={
                'unique_together': {('category_l', 'code')},
            },
        ),
        migrations.CreateModel(
            name='BudgetCategoryS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('category_m', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account_requests.budgetcategorym')),
            ],
            options={
                'unique_together': {('category_m', 'code')},
            },
        ),
        migrations.AddField(
            model_name='budget',
            name='budget_category_s',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account_requests.budgetcategorys'),
        ),
        migrations.CreateModel(
            name='BudgetAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attr_01', models.CharField(blank=True, max_length=200)),
                ('attr_02', models.CharField(blank=True, max_length=200)),
                ('attr_03', models.CharField(blank=True, max_length=200)),
                ('attr_04', models.CharField(blank=True, max_length=200)),
                ('attr_05', models.CharField(blank=True, max_length=200)),
                ('attr_06', models.CharField(blank=True, max_length=200)),
                ('attr_07', models.CharField(blank=True, max_length=200)),
                ('attr_08', models.CharField(blank=True, max_length=200)),
                ('attr_09', models.CharField(blank=True, max_length=200)),
                ('attr_10', models.CharField(blank=True, max_length=200)),
                ('attr_11', models.CharField(blank=True, max_length=200)),
                ('attr_12', models.CharField(blank=True, max_length=200)),
                ('attr_13', models.CharField(blank=True, max_length=200)),
                ('attr_14', models.CharField(blank=True, max_length=200)),
                ('attr_15', models.CharField(blank=True, max_length=200)),
                ('attr_16', models.CharField(blank=True, max_length=500)),
                ('attr_17', models.CharField(blank=True, max_length=500)),
                ('attr_18', models.CharField(blank=True, max_length=500)),
                ('attr_19', models.TextField(blank=True)),
                ('attr_20', models.TextField(blank=True)),
                ('budget', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account_requests.budget')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BudgetAttributeMultiValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multi_attr_type', models.CharField(choices=[('MULTI_01', 'MULTI_01'), ('MULTI_02', 'MULTI_02')], max_length=20)),
                ('value', models.CharField(max_length=500)),
                ('sort_order', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_requests.budget')),
            ],
        ),
    ]
