# Generated by Django 6.0.2 on 2026-02-18

import django.db.models.deletion
from django.db import migrations, models


def seed_asset_status_master(apps, schema_editor):
    AssetCategoryL = apps.get_model('account_requests', 'AssetCategoryL')
    AssetStatusMaster = apps.get_model('account_requests', 'AssetStatusMaster')
    AssetStatusTransitionMaster = apps.get_model('account_requests', 'AssetStatusTransitionMaster')

    default_statuses = [
        ('REQUESTED_FROM_IT', 'IT部依頼中（受領待ち）', 1),
        ('RECEIVED_WAITING', '受領済（配備待ち）', 2),
        ('WAITING_ASSIGNMENT', '利用者割当待ち', 3),
        ('IN_USE', 'ユーザー利用中', 4),
        ('RETURN_PENDING', '返却依頼中', 5),
        ('RETURNED', '返却済', 6),
        ('MAINTENANCE', '保守対応中', 7),
        ('REPAIRING', '修理中', 8),
        ('RETIRED_WAITING', '廃棄判定待ち', 9),
        ('DISPOSED', '廃棄済', 10),
    ]

    transition_pairs = [
        ('REQUESTED_FROM_IT', 'RECEIVED_WAITING'),
        ('RECEIVED_WAITING', 'WAITING_ASSIGNMENT'),
        ('WAITING_ASSIGNMENT', 'IN_USE'),
        ('IN_USE', 'RETURN_PENDING'),
        ('RETURN_PENDING', 'RETURNED'),
        ('RETURNED', 'WAITING_ASSIGNMENT'),
        ('IN_USE', 'MAINTENANCE'),
        ('MAINTENANCE', 'IN_USE'),
        ('MAINTENANCE', 'REPAIRING'),
        ('REPAIRING', 'MAINTENANCE'),
        ('IN_USE', 'RETIRED_WAITING'),
        ('IN_USE', 'DISPOSED'),
        ('RETURNED', 'RETIRED_WAITING'),
        ('MAINTENANCE', 'RETIRED_WAITING'),
        ('RETIRED_WAITING', 'DISPOSED'),
    ]

    for category_l in AssetCategoryL.objects.all():
        status_map = {}
        for code, name, order in default_statuses:
            status, _ = AssetStatusMaster.objects.get_or_create(
                category_l=category_l,
                status_code=code,
                defaults={'status_name': name, 'sort_order': order, 'is_active': True},
            )
            status_map[code] = status

        for from_code, to_code in transition_pairs:
            AssetStatusTransitionMaster.objects.get_or_create(
                category_l=category_l,
                from_status=status_map[from_code],
                to_status=status_map[to_code],
                defaults={'is_active': True},
            )


def rollback_asset_status_master(apps, schema_editor):
    AssetStatusTransitionMaster = apps.get_model('account_requests', 'AssetStatusTransitionMaster')
    AssetStatusMaster = apps.get_model('account_requests', 'AssetStatusMaster')
    AssetStatusTransitionMaster.objects.all().delete()
    AssetStatusMaster.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('account_requests', '0004_budget_category_and_attributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetStatusMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_code', models.CharField(max_length=40)),
                ('status_name', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('category_l', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account_requests.assetcategoryl')),
            ],
            options={
                'unique_together': {('category_l', 'status_code')},
            },
        ),
        migrations.CreateModel(
            name='AssetStatusTransitionMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category_l', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account_requests.assetcategoryl')),
                ('from_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transition_from', to='account_requests.assetstatusmaster')),
                ('to_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transition_to', to='account_requests.assetstatusmaster')),
            ],
            options={
                'unique_together': {('category_l', 'from_status', 'to_status')},
            },
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(default='IN_USE', max_length=40),
        ),
        migrations.RunPython(seed_asset_status_master, rollback_asset_status_master),
    ]
